# Generated by Django 4.0.3 on 2022-03-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')]),
        ),
    ]
