# Generated by Django 4.0.3 on 2022-03-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=False),
        ),
    ]
